### ISSUE TITLE
Google Map Issue

### ISSUE THREAD

**Issue by YoshiOri7** [smarty-sprouts/smarty-sprouts#22]
So I posted this earlier in Slack but I realize that you all may not be checking it regularly, so I am posting here (I think you will get this message in your email)

As I did more research on GoogleMap, I'm starting think that it's probably better to just use GoogleMap API over Anguler-GoogleMap API (We will still use Angular on the FrontEnd but use GoogleMap API in HTML).  I found more examples on GoogleMap API in general (vs Angular-GoogleMap API).  I've also set up map using both ways, and I found GoogleMap API is easier. 

 It might be painful to switch but it will likely pay dividends later on.  Let's discuss this tomorrow.

Angular-Google-Map Doc:
http://angular-ui.github.io/angular-google-maps/#!/

GoogleMaps API Doc: 
https://developers.google.com/maps/documentation/javascript/tutorial

Good Reference:
https://scotch.io/tutorials/making-mean-apps-with-google-maps-part-i

**Comment by wilsonhyng** [comment]
We ended up choosing to go with the Google Map API over the Angular-GoogleMap.
