### ISSUE TITLE
Cleanup Public Folder

### ISSUE THREAD

**Issue by YoshiOri7** [smarty-sprouts/smarty-sprouts#42]
- remove index.html in Public folder? (we have index.html in Views folder now)
- remove node_modules and package.son in Public folder (I put it there initially but I don't think we need it anymore)
- move Yoshi's API key to config.js and inlcude config.js in .gitignore file
- remove more unused files

**Comment by wilsonhyng** [comment]
Still need to hide API key properly.

We are currently limiting the API key access to only certain IP addresses (ie Hack Reactor).
